### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by benkaiser** [saschagehlich/node-eyed3#1]
I have been writing a benchmark of various different node.js id3 tag readers and wish to  include yours. however when I run eyed3.readMeta I get an exit code of 1. Here is the code I am using:

```
var EyeD3 = require('eyed3');
var eyed3 = new EyeD3();

eyed3.readMeta(track, function (err, meta) {
  console.log(err);
  console.log(meta);
});
```

output is:

```
[Error: eyeD3 exit code: 1]
undefined
```

**Comment by saschagehlich** [comment]
Have you installed `eyed3` on your system or only `node-eyed3`?

**Comment by benkaiser** [comment]
In npm I have `eyed3` installed. My package.json:

```
{
 ...
"dependencies" : {
    "eyed3": "*",
    "benchmark": "*",
    "microtime": "*"
  }
}
```

As for the system package I have eyeD3 installed:

```
$ pacman -Qs eyeD3
local/python2-eyed3 0.7.3-2
    A Python module and program for processing information about mp3 files
```

It can be executed with `eyeD3``:

```
$ eyeD3 song.mp3 
song.mp3    [ 6.06 MB ]
-------------------------------------------------------------------------------
Time: 02:36 MPEG1, Layer III    [ 320 kb/s @ 44100 Hz - Joint stereo ]
-------------------------------------------------------------------------------
ID3 v2.4:
title: Hawaiian Punch
artist: Social Club
album: MISFIT B-Sides
recording date: 2012
track: 1        
Comment: [Description: ] [Lang: eng]
Visit http://martymar.goodcitymusic.com
Lyrics: [Description: None] [Lang: eng]
Twitter.com/deathbymartmar
FRONT_COVER Image: [Size: 118604 bytes] [Type: image/jpeg]
Description: cover

-------------------------------------------------------------------------------
```

**Comment by saschagehlich** [comment]
Could you try to clone the repository, do `npm install` and run `make test`?

**Comment by vikbez** [comment]
```
$>eyeD3 --version
eyeD3 0.6.18 (C) Copyright 2002-2011 Packaged by Homebrew
This program comes with ABSOLUTELY NO WARRANTY! See COPYING for details.
Run with --help/-h for usage information or see the man page 'eyeD3(1)'

$>make test          


  EyeD3
    ✓ should correctly generate the command line arguments 
    ✓ should correctly read the meta data of an .mp3 file (222ms)
    ✓ should correctly update the meta data of an .mp3 file (287ms)


  3 passing (515ms)

```

```
$>eyeD3 --version     
eyeD3 0.7.4-beta (C) Copyright 2002-2013 Travis Shirk
This program comes with ABSOLUTELY NO WARRANTY! See COPYING for details.
Run with --help/-h for usage information or read the docs at
http://eyeD3.nicfit.net

$>make test           


  EyeD3
    ✓ should correctly generate the command line arguments 
    1) should correctly read the meta data of an .mp3 file
    2) should correctly update the meta data of an .mp3 file


  1 passing (482ms)
  2 failing

  1) EyeD3 should correctly read the meta data of an .mp3 file:
     Uncaught Error: eyeD3 exit code: 1
      at ChildProcess.<anonymous> (/Users/v/TEST/node-eyed3/index.js:27:23)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at Process.ChildProcess._handle.onexit (child_process.js:797:12)

  2) EyeD3 should correctly update the meta data of an .mp3 file:
     Uncaught Error: eyeD3 exit code: 1
      at ChildProcess.<anonymous> (/Users/v/TEST/node-eyed3/index.js:27:23)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at Process.ChildProcess._handle.onexit (child_process.js:797:12)



make: *** [test] Error 2
```

this is due to the fact that the option --rfc822 no more exists 
https://github.com/saschagehlich/node-eyed3/blob/master/index.js#L17

maybe we can work on something to add support for newest version ..
(because just removing --rfc822 arg can cause some data to be misread, like comment field)

**Comment by benkaiser** [comment]
@saschagehlich any update on this issue? I would love to be able to use your library in my project as it does both reading and writing of tags.
